FROM node:8-slim
COPY --from=yfei1/base /whalesRebuild /whalesRebuild

RUN echo "#!/bin/sh\nncu -u\nnpm install\nnpm run dev" >> start.sh
RUN chmod 777 start.sh

WORKDIR /whalesRebuild
RUN npm install -g npm-check-updates


ENTRYPOINT ["/start.sh"]
